name: Terraform plan

on:
  pull_request:
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - ".github/workflows/*.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: read

jobs:
  plan:
    name: Terraform plan (${{ matrix.environment }})
    strategy:
      fail-fast: false
      matrix:
        environment:
          - dev
          - prod

    uses: ./.github/workflows/terraform-plan-reusable.yml
    permissions:
      contents: read
      id-token: write
      pull-requests: read
    with:
      environment: ${{ matrix.environment }}
      artifact_name: pr-tfplan
    secrets: inherit
