name: Terraform plan

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: read

jobs:
  plan:
    name: Terraform plan (pr)
    uses: ./.github/workflows/terraform-plan-reusable.yml
    permissions:
      contents: read
      id-token: write
      pull-requests: read
    with:
      environment: dev
      deploy_to_env: false
      artifact_name: pr-tfplan
    secrets: inherit

  scan:
    name: Scan plan for misconfigs
    needs: plan
    uses: ./.github/workflows/iac-scan.yml
    with:
      artifact_name: ${{ needs.plan.outputs.artifact_name }}
      environment: dev



